export const TECH_KEYWORDS = [
  'api', 'frontend', 'backend', 'docker', 'kubernetes', 'k8s',
  'git', 'deploy', 'ci', 'cd', 'pipeline', 'database', 'db',
  'redis', 'postgres', 'prisma', 'graphql', 'rest', 'grpc',
  'react', 'next', 'nextjs', 'vue', 'angular', 'svelte',
  'node', 'nestjs', 'express', 'fastify', 'typescript', 'ts',
  'javascript', 'js', 'python', 'go', 'rust', 'java',
  'aws', 'gcp', 'azure', 'vercel', 'netlify', 'cloudflare',
  'terraform', 'ansible', 'helm', 'argocd', 'jenkins',
  'nginx', 'caddy', 'traefik', 'kong', 'envoy',
  'kafka', 'rabbitmq', 'sqs', 'pubsub',
  'elasticsearch', 'kibana', 'grafana', 'prometheus',
  'auth', 'oauth', 'jwt', 'sso', 'rbac',
  'mfe', 'microfrontend', 'microservice', 'monorepo',
  'storybook', 'figma', 'design-system', 'ds',
  'refactor', 'hotfix', 'bugfix', 'feature', 'release',
  'pr', 'mr', 'code-review', 'squash', 'rebase',
  'performance', 'cache', 'cdn', 'ssl', 'dns',
  'monitoring', 'logging', 'tracing', 'observability',
  'testing', 'e2e', 'unit', 'integration', 'vitest', 'jest', 'cypress',
];
